#!/bin/sh

read -p "Do you want to continue? [y|N]" -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi
echo ""
echo "Cleaning up"

find ./out -type d -empty -delete

for file in $(find out -type f -name "*-std.*"); do
    shortname=$(echo $file | pcregrep -o1 "(.+)-std\.")
    corresponding_dir=$(find out -maxdepth 1 -path "$shortname*" -type d)
    if [[ ! $corresponding_dir ]]; then
        echo Removing $file because no corresponding non-empty directory exists
        rm $file
    else
        mv $file $corresponding_dir
    fi
    
done
