#!/bin/sh
#SBATCH --partition=maxgpu ## or allgpu / cms / cms-uhh / maxgpu
#SBATCH --time=03:00:00
#SBATCH --nodes=1
#SBATCH --job-name interpol_latent           # give job unique name
#SBATCH --output ./interpol_latent_log/%j-std.out      # terminal output
#SBATCH --error ./interpol_latent_log/%j-std.err
#S BATCH --mail-type END
#S BATCH --mail-user lennart.kaemmle@desy.de
#SBATCH --constraint=GPU

# #SBATCH --nodelist=max-cmsg004         # you can select specific nodes, if necessary
#SBATCH --constraint="P100|V100"        # ask for specific types of GPUs

# (GPU drivers, anaconda, .bashrc, etc) --> likely not necessary if you're installing your own cudatoolkit & cuDNN versions
#source /etc/profile.d/modules.sh
#module load maxwell
#module load cuda
#module load anaconda/3
#module load mpi/mpich-x86_64
# module load mpi/openmpi3-x86_64

. ~/.bashrc
export PATH="/home/kaemmlel/miniconda3/envs/torch/bin:$PATH"

set -x
# export PATH="/home/kaemmlel/miniconda3/envs/torch/bin:$PATH"
export PYTHONPATH=""  # openmpi module adds python 2 packages to pythonpath

# Recipe for gloo protocol
#export MASTER_HOST=$(hostname -i)
#export MASTER_PORT=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')

# go to your folder with your python scripts
cd ~/Projects/amazing_ai

# START=s
# END=b
# --file-end @events_${END}_sr.h5 \
# --a-to-a \

time python -m amazing_ai.scripts.interpol_latent \
        --file-start @events_b_sr.h5 @events_s_sr.h5 --n-starts 1000 1000 \
        --file-end @events_b_sr.h5 --n-ends 1000 \
        --steps 100 --npix 42 \
        --interpol-radius 2 \
        -o @interpol_latent/{interpol_radius}/interpol_{jobid}_any-b_{n_starts}_{n_ends}_im={interpol_method}_ir={interpol_radius}{flags}.h5 \
        --model models/13554747_model=1_npix=42_ts=0.6_data=@events_b_sr_images_42_center_hist.h5_noise=0.0008_ls=40
        # --rotate --flip
        # --model models/13170844_model=1_npix=42_ts=0.6_data=@events_b_sr_images_42_center_rotate_flip_hist.h5_noise=0.0008_ls=40
        # --interpol-radius 7 \
        # --model out/12139736*/
#        --interpol-radius 200 \
# _ir={interpol_radius}

# time python -m amazing_ai.scripts.interpol_latent \
#         --file-start @events_b_sr.h5 @events_s_sr.h5 \
#         --n-starts 2000 2000 \
#         --file-end @events_b_sr.h5 \
#         --n-ends 600 \
#         -o @interpol_any-b_{n_starts}_{n_ends}_im={interpol_method}_ir={interpol_radius}{flags}.h5 \
#         --steps 100 \
#         --rotate --flip --npix 42 \
#         --model models/13170844_model=1_npix=42_ts=0.6_data=@events_b_sr_images_42_center_rotate_flip_hist.h5_noise=0.0008_ls=40
#         # --interpol-radius 7 \
#         # --model out/12139736*/
# #        --interpol-radius 200 \
# # _ir={interpol_radius}
